### PR TITLE
Initial set up instructions

### PR DESCRIPTION
**Pull request by tbelaire**
I've added the initial set up instructions.

### CODE REVIEW

**Comment by hkpeprah** [comment]
Maybe setups for setting up virtualenv?
E.g. on Mac  

1.  Install [homebrew](http://brew.sh/) if you don't already have it.
2.  Setup your environment.
```
$ brew install python
$ pip install virtualenv virtaulenvwrapper
$ export WORKON_HOME=~/.envs
$ echo "export WORKON_HOME=~/.envs" >> .bash_profile
$ mkdir -p $WORKON_HOME
$ source /usr/local/bin/virtualenvwrapper.sh
$ echo "source /usr/local/bin/virtualenvwrapper.sh" >> .bash_profile
$ mkvirtualenv math
$ workon math
```

**Comment by tbelaire** [comment]
So, I actually have failed to install `virtualenvwrapper` myself, and it's currently broken on my machine, so maybe you could add that section.

**Comment by hkpeprah** [comment]
Sure, I'll open as a separate PR in awhile.

**Comment by tbelaire** [comment]
Well, I did manage to get `workon` working-ish.

Unfortunately, while my output of 
```
$ pip show Django
---
Metadata-Version: 2.0
Name: Django
Version: 1.8.2
Summary: A high-level Python Web framework that encourages rapid development and clean, pragmatic design.
Home-page: http://www.djangoproject.com/
Author: Django Software Foundation
Author-email: foundation@djangoproject.com
License: BSD
Location: /usr/local/lib/python2.7/site-packages
Requires: 
```

Shows it to be installed,
```
⚡ python 
Python 2.7.9 (default, Apr  7 2015, 07:58:25) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import django
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named django
>>> 
```
Fails for some reason.

**Comment by hkpeprah** [comment]
If you're in the virtual environment, you'll probably need to install the requirements again.

```
$ workon math
$ pip install -r requirements.txt
```

**Comment by tbelaire** [comment]
```
Requirement already satisfied (use --upgrade to upgrade): Django==1.8.2 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 1))
```

**Comment by hkpeprah** [comment]
Hm, weird.

**Pull request merged**
